language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev
script:
  - nproc
  - qmake -qt=qt4 -v
  - qmake -qt=qt5 -v
  - ./configure -verbose -qmake `qmake -qt=qt4 -query QT_INSTALL_BINS`/qmake -var "QMAKE_CXX=${CXX}" -var "QMAKE_CC=${CC}"
  - make -j$(nproc)
  - make check
  - sudo make install
  - cd tests/build
  - qmake -qt=qt4 && make
  - cd -
  - git clean -xdf
  - ./configure -verbose -qmake `qmake -qt=qt5 -query QT_INSTALL_BINS`/qmake -var "QMAKE_CXX=${CXX}" -var "QMAKE_CC=${CC}"
  - make -j$(nproc)
  - make check
  - sudo make install
  - cd tests/build
  - qmake -qt=qt5 && make
